# Generated by Django 6.0.5 on 2026-05-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
