# Generated by Django 6.0.5 on 2026-05-18 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wishlist_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('Warehouse', 'Main Warehouse'), ('Retail', 'Retail Branch'), ('Popup', 'Pop-up Store')], default='Retail', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='negotiated_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('Web', 'Online Store'), ('POS', 'Point of Sale')], default='Web', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Stripe', 'Stripe'), ('WhatsApp-Pending', 'WhatsApp-Pending'), ('POS-Cash', 'POS Cash'), ('POS-Transfer', 'POS Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Sale', 'Sale'), ('Transfer', 'Transfer'), ('Adjustment', 'Stock Adjustment'), ('Return', 'Customer Return'), ('Restock', 'Restock')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='core.store')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.store'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.store')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
