# Generated by Django 6.0.5 on 2026-05-18 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_order_negotiated_discount_order_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='source',
            new_name='order_source',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='store',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='from_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='core.store'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='to_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='core.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Stripe', 'Stripe'), ('WhatsApp-Pending', 'WhatsApp-Pending'), ('Cash', 'Cash'), ('POS-Terminal', 'POS Terminal'), ('Transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
