# Generated by Django 6.0.5 on 2026-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_source_order_order_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Super Admin'), ('Manager', 'Store Manager'), ('Attendant', 'Store Attendant'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
